name: square equation test

on:
  push:
    branches: ["XUNIT"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib/

      - name: Build
        run: dotnet build SquareEquationLib/ --no-restore /p:ContinuousIntegrationBuild=true

      - name: Unittest and coverage
        run: dotnet test /p:CoverletOutputFormat=cobertura /p:CollectCoverage=true /p:ThresholdType=line /p:Threshold=100
